logging:
  file:
    name: logs/application.log
operations:
  interval: 1000

sensor:
  distance:
    #pin: 0
  motion:
    pin: 1
    interval: 1000
  sound:
    pin: 2
    interval: 1000

motion:
  track:
    pin:
      right:
        front: 3
        rear: 4
      left:
        #front: 5
        front: 25
        #rear: 6
        rear: 26

remote:
  controllerUrl: ws://bobby-remote-stage.herokuapp.com/client
