version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run gradle dependencies
          command: |
            ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Run unit tests
          command: |
            ./gradlew test
#      - run:
#          name: Run integration tests
#          command: |
#            ./gradlew integrationTest
      - run:
          name: Build fat jar
          command: |
            ./gradlew clean jar
      - store_artifacts:
          path: ~/repo/build/libs
